author: "VincentJiang"
meta:
  description: "这是Vincentjiang的博客, VincentJiang是居住在深圳的一名 Ruby 程序员,是Ruby On Rails的狂热爱好者，希望日后成为一位杰出的全栈开发人员"
  keywords: "Vrails, VincentJiang, Rails, Ruby On Rails, RoR"
qtniu_bucket_domain: "http://xxxxx.xxxxx.com"
newrelic:
  key: "xxxxxxxxxxxxxxxxxxxxxxxxx"
